In [1]:
import pandas as pd

In [2]:
data_path="datasets/real/2019-10-18/raw/coords-2019-10-18-20-40-59.txt"

In [3]:
df = pd.DataFrame()

with open(data_path, 'r') as f:
    for line in f:
        df = pd.concat( [df, pd.DataFrame([tuple(line.strip().split(' '))])], ignore_index=True )

In [4]:
columns =["command","1","2","3","4","5","6","7","8"]

In [5]:
df.columns=columns

In [6]:
df.head()

  command       1      2      3      4      5    6    7    8
0       f  79.685  -4857  -5925  -3116  -9975  NaN  NaN  NaN
1             NaN    NaN    NaN    NaN    NaN  NaN  NaN  NaN
2       f  79.685  -4857  -5925  -3116  -9975  NaN  NaN  NaN
3             NaN    NaN    NaN    NaN    NaN  NaN  NaN  NaN
4       f  79.685  -4857  -5925  -3116  -9975  NaN  NaN  NaN

In [7]:
df.columns

Index(['command', '1', '2', '3', '4', '5', '6', '7', '8'], dtype='object')

In [25]:
f_df = df[df.command=="f"]

In [26]:
m_df= df[df.command=="m"]

In [11]:
m_df.head()

,command,1,2,3,4,5,6,7,8
214,m,-1,-1048.6762597547424,-1137.0371245723154,1035.8479897419506,1609.6041510677978,NaN,NaN,NaN
215,m,-1,-1048.6762597547424,-1137.0371245723154,1035.8479897419506,1609.6041510677978,NaN,NaN,NaN
218,m,-1,-1048.6762597547424,-1137.0371245723154,1035.8479897419506,1609.6041510677978,NaN,NaN,NaN
219,m,-1,-1048.6762597547424,-1137.0371245723154,1035.8479897419506,1609.6041510677978,NaN,NaN,NaN
222,m,-1,-1048.6762597547424,-1137.0371245723154,1035.8479897419506,1609.6041510677978,NaN,NaN,NaN

In [12]:
columns=list(m_df.columns)

In [13]:
columns[1]="TS"

In [14]:
columns

['command', 'TS', '2', '3', '4', '5', '6', '7', '8']

In [15]:
m_df.columns=columns

In [28]:
m_df.drop(labels="command",axis=1,inplace=True)

C:\Users\sezan92\Anaconda3\lib\site-packages\pandas\core\frame.py:3940: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  errors=errors)

In [29]:
m_df = m_df.astype("float")

In [30]:
m_df.head()

       1           2            3           4            5   6   7   8
214 -1.0 -1048.67626 -1137.037125  1035.84799  1609.604151 NaN NaN NaN
215 -1.0 -1048.67626 -1137.037125  1035.84799  1609.604151 NaN NaN NaN
218 -1.0 -1048.67626 -1137.037125  1035.84799  1609.604151 NaN NaN NaN
219 -1.0 -1048.67626 -1137.037125  1035.84799  1609.604151 NaN NaN NaN
222 -1.0 -1048.67626 -1137.037125  1035.84799  1609.604151 NaN NaN NaN

In [31]:
p_df=df[df.command=="p"]

In [32]:
p_df.head()

,command,1,2,3,4,5,6,7,8
223,p,0.081,0.6142554636828396,-0.048132980325083966,-0.23761772242417836,0.7509404104188294,-80.538089,151.885025,-901.142281
224,p,0.153,0.600128016692024,-0.1535951552526949,-0.2354966361214309,0.7488631383637467,-76.42949,143.322715,-851.503675
226,p,0.184,0.6006678209588578,-0.14963221859609485,-0.23410726905148482,0.7496680932252618,-76.751105,144.132916,-856.223373
227,p,0.214,0.6010342751758302,-0.1486051661164681,-0.23563637169464935,0.7490991256168973,-76.686928,144.151836,-856.208015
228,p,0.243,0.6004295401557352,-0.1465971394028194,-0.23938881969412712,0.7487901909079738,-76.753491,144.142473,-856.56746

In [33]:
p_df.drop(labels="command",axis=1,inplace=True)

In [34]:
p_df.astype("float")

,1,2,3,4,5,6,7,8
223,0.081,0.614255,-0.048133,-0.237618,0.750940,-80.538089,151.885025,-901.142281
224,0.153,0.600128,-0.153595,-0.235497,0.748863,-76.429490,143.322715,-851.503675
226,0.184,0.600668,-0.149632,-0.234107,0.749668,-76.751105,144.132916,-856.223373
227,0.214,0.601034,-0.148605,-0.235636,0.749099,-76.686928,144.151836,-856.208015
228,0.243,0.600430,-0.146597,-0.239389,0.748790,-76.753491,144.142473,-856.567460
232,0.273,0.612456,-0.045004,-0.250765,0.748324,-80.268849,151.459879,-898.947621
233,0.302,0.607228,-0.071676,-0.264311,0.745839,-79.374820,149.675450,-888.689296
234,0.332,0.600401,-0.148757,-0.235748,0.749542,-76.865396,144.371244,-857.717096
235,0.363,0.600378,-0.146836,-0.237615,0.749350,-76.772969,144.315339,-857.356877
237,0.395,0.600860,-0.150404,-0.233556,0.749532,-76.826892,144.284244,-857.199504
238,0.427,0.601438,-0.152677,-0.230454,0.749569,-77.031637,144.630593,-859.336101
239,0.463,0.600626,-0.148929,-0.236108,0.749214,-76.770610,144.268736,-857.067744
243,0.494,0.600835,-0.147532,-0.235084,0.749644,-76.891266,144.440172,-857.789528
244,0.527,0.601208,-0.145825,-0.235668,0.749496,-76.880257,144.510720,-858.139620
245,0.563,0.601093,-0.146442,-0.237153,0.748999,-76.855922,144.408874,-858.055814
247,0.594,0.600726,-0.148040,-0.235644,0.749456,-76.884284,144.329441,-857.409279
248,0.627,0.600731,-0.147085,-0.235958,0.749541,-76.826430,144.391404,-857.880343
249,0.663,0.600726,-0.150422,-0.235287,0.749094,-76.826643,144.228038,-856.739712
253,0.695,0.614655,-0.035049,-0.240435,0.750441,-80.534050,152.254963,-903.169014
254,0.727,0.601131,-0.149963,-0.235578,0.748770,-76.743067,144.206851,-856.597973
255,0.763,0.599926,-0.150419,-0.236844,0.749245,-76.799744,144.208138,-856.521571
257,0.795,0.600708,-0.144448,-0.237744,0.749508,-76.880273,144.424209,-857.902029
258,0.827,0.602036,-0.149716,-0.236055,0.747941,-75.925036,142.468617,-845.630283
259,0.863,0.600959,-0.153606,-0.231379,0.749478,-75.990350,142.456920,-845.798205
263,0.895,0.601803,-0.149360,-0.231795,0.749531,-75.962576,142.480876,-846.112166
264,0.927,0.601688,-0.148003,-0.237138,0.748220,-75.825241,142.267169,-844.807840
265,0.963,0.601915,-0.151636,-0.231518,0.749069,-75.940170,142.481101,-845.755886
267,0.994,0.601115,-0.155124,-0.233030,0.748529,-75.944609,142.444267,-845.705090
268,1.026,0.601213,-0.151486,-0.236056,0.748247,-75.915330,142.503872,-845.705636
269,1.063,0.600362,-0.155069,-0.231964,0.749474,-75.994628,142.601544,-846.464342
...,...,...,...,...,...,...,...,...
1538,40.020,0.629101,-0.154992,-0.304002,0.698421,113.918027,84.272537,-832.601614
1542,40.101,0.632256,-0.150539,-0.301687,0.697549,114.988913,84.653753,-833.687428
1543,40.182,0.638509,-0.150779,-0.294059,0.695055,116.764900,85.119587,-837.113313
1545,40.264,0.635923,-0.153304,-0.305986,0.691717,116.613645,84.949595,-831.415025
1549,40.344,0.632269,-0.156619,-0.304949,0.694776,117.018332,84.958328,-832.163537
1551,40.425,0.628541,-0.146401,-0.309867,0.698202,117.623478,85.087226,-834.529679
1555,40.507,0.627757,-0.155200,-0.310170,0.696871,117.572425,84.729321,-832.241878
1556,40.588,0.632012,-0.153883,-0.302262,0.696792,118.319228,84.929846,-833.723123
1558,40.669,0.635984,-0.154393,-0.303115,0.692682,118.344536,84.714564,-831.232349
1562,40.749,0.639277,-0.153233,-0.304914,0.689110,118.090199,84.351612,-828.256326
1564,40.830,0.638171,-0.151992,-0.306466,0.689721,117.738927,84.230717,-827.723931
1568,40.911,0.632620,-0.153423,-0.301928,0.696486,118.052027,85.235987,-836.425811
1569,40.992,0.628417,-0.155958,-0.304883,0.698438,117.106639,85.008330,-834.529028
1571,41.073,0.626694,-0.154989,-0.308423,0.698647,116.600593,84.892833,-833.957387
1575,41.154,0.628958,-0.153865,-0.304813,0.698445,116.528224,85.042254,-835.556397
1577,41.235,0.631893,-0.156261,-0.302017,0.696476,116.550865,85.130586,-835.698125
1581,41.316,0.635916,-0.154940,-0.303081,0.692638,116.156450,84.856733,-832.835839
1582,41.397,0.635513,-0.152112,-0.303572,0.693419,116.348331,84.934295,-834.047618
1584,41.478,0.631197,-0.153007,-0.300616,0.698433,116.576900,85.292946,-837.311397
1588,41.559,0.628391,-0.155988,-0.307535,0.697291,116.175983,85.078286,-834.631036
1590,41.640,0.626312,-0.151638,-0.311101,0.698538,116.141910,84.847853,-833.002641
1594,41.725,0.629676,-0.156019,-0.305700,0.696931,116.754743,84.835874,-833.348275
1596,41.806,0.632618,-0.154181,-0.301585,0.696469,117.541061,84.949036,-834.717850
1597,41.887,0.637677,-0.150350,-0.302917,0.692101,117.817113,84.578277,-831.415114
1601,41.970,0.636808,-0.153240,-0.302442,0.692476,117.831981,84.463007,-830.078374
1603,42.051,0.633119,-0.156717,-0.306241,0.693409,117.870923,84.464677,-831.084768
1607,42.133,0.631013,-0.149301,-0.304397,0.697764,118.546973,85.077091,-837.132578
1609,42.215,0.628833,-0.155101,-0.306244,0.697658,117.554880,84.664924,-832.666742
1610,42.297,0.629976,-0.149392,-0.306097,0.697937,117.980914,85.069575,-836.396923
1614,42.378,0.631813,-0.151762,-0.307735,0.695040,117.433262,84.667637,-832.862054

In [35]:
m_df.shape

(427, 8)

In [36]:
p_df.shape

(551, 8)

In [ ]:
p_df.shape

In [ ]:
m_df.shape